config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'
  get 'contact/show'
  get 'about/show'
  get 'flowers/index'
  get 'flowers/show'

  root to: "home#index"

  get "/about", to: "about#show"
  get "/contact", to: "contact#show"

  get '/index', to:'home#index'
  get '/sale', to:'home#sale'
  get '/new' , to:'home#new'

  resources :flowers, only: [:index, :show] do
    collection do
      get "search"
    end
  end

  post "/cart/checkout", to:'cart#checkout'

  resources :items
  resources :orders
  resources :cart, only: [:create, :checkout, :destroy, :index, :update]
  resources :home
  resources :category

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/about.rb
class About < ApplicationRecord
  validates :description, presence: true
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :order, optional: true
  belongs_to :flower

  validates :price, :quantity, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 0}
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true

  has_many :flowers
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :description, presence:true
end

app/models/customer.rb
class Customer < ApplicationRecord
  validates :username, :password, :role, :first_name, :last_name, :email, :address, presence: true

  belongs_to :province
end

app/models/flower.rb
class Flower < ApplicationRecord

  has_many :cart_items
  belongs_to :category

  validates :name, :price, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 0}

  has_one_attached :image
end

app/models/order.rb
class Order < ApplicationRecord
  validates :subtotal, :total, :status, presence: true
  validates :pst, :gst, :hst, :total, numericality: { greater_than_or_equal_to: 0}

  belongs_to :user
  has_many :cart_items
end

app/models/province.rb
class Province < ApplicationRecord
  validates :name, presence: true
  validates :pst, :gst, :hst, numericality: { greater_than_or_equal_to: 0}

  has_many :customers
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :province
  has_many :orders
end

app/controllers/cart_controller.rb
class CartController < ApplicationController

  def create
    logger.debug("Adding #{params[:id]} to cart.")
    id = params[:id].to_i

    unless session[:shopping_cart].include? (id)
      session[:shopping_cart][id] = 1 # push id onto the end of the cart array
      product = Flower.find(id)
      flash[:notice] = "+ #{product.name} added to cart."

      redirect_to root_path
    end

  end

  def update
    id = params[:id].to_i
    quantity = params[:quantity].to_i

    if (quantity < 1)
      session[:shopping_cart].delete(id)
    else
      session[:shopping_cart]["#{id}"] = quantity;
    end

    redirect_to cart_index_path
  end

  def destroy
    id = params[:id].to_i
    session[:shopping_cart].delete("#{id}")
    product = Flower.find(id)
    flash[:notice] = "- #{product.name} removed from cart."
    redirect_to root_path
  end

  def index
   @cart = Flower.find(session[:shopping_cart].keys)
  end

  def checkout
    items = session[:shopping_cart]
    subtotal = params[:subtotal]
    pst = params[:pst]
    gst = params[:gst]
    hst = params[:hst]
    total = params[:total]
    status = "paid"

    if user_signed_in?
      order = Order.create(
        subtotal: subtotal,
        pst:      pst,
        gst:      gst,
        hst:      hst,
        status:   status,
        total:    total,
        user:     current_user
      )

      if order && order.valid?
        items.each do |id, quantity|
          flower = Flower.find(id)
          price = flower.price
          if(flower.sale_price.present?)
            price = flower.sale_price
          end

          cart_items = order.cart_items.create(
            price: price,
            quantity: quantity,
            flower_id: id
          )

        end

        session[:shopping_cart].clear
      end

      flash[:notice] = "Order Completed!"
      redirect_to home_index_path
    else
      redirect_to new_user_session_path
    end


  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController


  def index
    @flowers = Flower.page(params[:page]);

    # add_breadcrumb "All", index_path
  end

  def sale
    @flowers = Flower.where("sale_price IS NOT NULL").page(params[:page])

    add_breadcrumb "Sale", sale_path
  end

  def new
    three_days_ago = DateTime.now - 3.days
    @flowers = Flower.where("created_at > ?", three_days_ago).page(params[:page])

    add_breadcrumb "New", sale_path
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/flowers_helper.rb
module FlowersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/cart/_cartitem.html.erb
<div class="block ml-5">
        <% @cart.each do |flower| %>
        <div class="box p-5">
          <article class="columns is-desktop p-2">
            <div class="column has-text-centered">
                <%= image_tag(flower.image, alt: flower.name, style: "width: 100%")%>
            </div>
            <div class="column">
              <div class="content m-1 has-text-centered">
                <h2 class="title is-4" ><%= flower.name %></h2>

                <% if flower.sale_price.present? %>
                  <h3 class="subtitle is-5">$<%= flower.sale_price%></h3>
                  <h3 class="subtitle is-6" style="text-decoration: line-through">$<%= flower.price%></h3>
                <% else %>
                  <h3 class="subtitle is-5">$<%= flower.price%></h3>
                <% end %>
              </div>
              <div class="mt-4">

                    <%= form_with url: cart_path(flower.id), method: :put do %>
                      <% quantity = session[:shopping_cart]["#{flower.id}"] %>
                      <div class="is-flex is-justify-content-center">
                        <p class="m-3">Qty: </p><%= number_field_tag(:quantity, quantity, id: flower.id, class: " input m-1", style: "width: 50px", min: "0") %>
                      </div>
                      <%= hidden_field_tag :id, flower.id, :id => Random.rand %>
                      <div class="is-flex is-justify-content-center">
                      <%= button_tag 'Update', class: "button is-link is-responsive mt-4" %>
                      </div>
                  <% end %>


              </div>
            </div>
            <div class="column is-narrow has-text-right">

                                        <% if cart.include?(flower) %>
                                          <%= button_to cart_path(flower.id), class: "button is-danger p-3", method: :delete do %>
                                            x
                                          <% end %>
                                        <% end %>
                                      </div>

          </article>
        </div>

        <% end %>




</div>

app/views/cart/_summary.html.erb
<div class="box m-6">
<% subtotal = 0 %>
  <div class="field">
    <label class="label">Order Summary</label>
    <% @cart.each do |f|%>
    <div class="control">
      <p><%= f.name %></p>
      <p class="has-text-right">
        <% if f.sale_price.present?
            price = f.sale_price
          else
            price = f.price
          end %><%= number_to_currency(price) %>
        <% quantity = session[:shopping_cart]["#{f.id}"]
        if (quantity > 1) %>
         x <%= quantity %>
        <% end %>
        <% subtotal += price * quantity %>
      </p>
    </div>
    <% end %>
  </div>

<hr>
  <% if user_signed_in?
      province = Province.find(User.find(current_user.id).province_id)
      pst = province.pst * subtotal
      gst = province.gst * subtotal
      hst = province.hst * subtotal
    else
      manitoba = Province.where("name == 'Manitoba'").first
      if (manitoba)
      pst = manitoba.pst * subtotal
      gst = manitoba.gst * subtotal
      hst = manitoba.hst * subtotal
      end
    end
    %>
  <div class="field">
    <label class="label">Sub Total: </label>
    <div class="control">
      <p class="has-text-right title is-6"><%= number_to_currency(subtotal) %></p>
    </div>
    <p class="has-text-right">GST: &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;<%= number_to_currency(gst)%> </p>
    <p class="has-text-right">HST: &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;<%= number_to_currency(hst)%> </p>
    <p class="has-text-right">PST: &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;<%= number_to_currency(pst)%> </p>
<hr>
  <label class="label"> Total: </label>
    <div class="control">
      <p class="has-text-right title is-4"><%= number_to_currency(total = subtotal + gst + hst + pst) %></p>
    </div>
  </div>

<%= form_with url: cart_checkout_path, method: :post do %>
  <%= hidden_field_tag(:subtotal, subtotal) %>
  <%= hidden_field_tag(:total, total)%>
  <%= hidden_field_tag(:hst, hst)%>
  <%= hidden_field_tag(:gst, gst)%>
  <%= hidden_field_tag(:pst, pst)%>
  <%= button_tag 'Checkout', class: "button is-primary", style: "width: 100%" %>
<% end %>
</div>

app/views/cart/index.html.erb
<div class="block p-6" style="background-color: #F2C8AD"><h1 class="title is-1" style="font-family: Dancing Script; color: #AA7485">Shopping Cart</h1></div>

<div class="columns is-desktop">

<% if session[:shopping_cart].present? %>
  <div class="column" >
    <%= render "cart/cartitem" %>
  </div>

  <div class="column" >
    <%= render "cart/summary" %>
  </div>
<% else %>
  <div class="box m-auto">
    <p> No items in your shopping cart</p>
 </div>
<% end %>

</div>

app/views/home/_template.html.erb
<div class="columns">
    <p class="subtitle is-2 m-auto p-4" style="font-family: Dancing Script">Know what you're looking for? </p>

    <div  class="is-active m-auto p-3">
      <div class="m-auto">
          <div class="field has-addons has-addons-centered">
            <%= form_with(url: search_flowers_path, method: :get, local: true) do %>
            <div class="field has-addons has-addons-right">
              <p class="control">
              <% categories_array = Category.all.map { |s| [s.name.capitalize, s.id]}%>
              <% categories_array.unshift(["All", "all"])%>
                <span class="select">
                  <%= select_tag(:type, options_for_select(categories_array, selected: "All"))%>
                </span>
              </p>
              <p class="control">
                <%= text_field_tag(:searchwords, nil, class: "input", placeholder: 'ex. Roses, Tulips') %>
              </p>
              <p class="control">
                <%= submit_tag("Search", class: "button is-light", style: "background-color: #A79BAE; color: white")%>
              </p>
            </div>

            <% end %>
            </div>
        </div>
      </div>
</div>

app/views/home/index.html.erb
<div class="block"> <%=  image_tag("background.jpg", alt: "flower shop")  %></div>


<div class="block p-4">

<%= render 'home/template' %>

<div class="block m-auto is-centered">
  <%= link_to 'ALL', root_path, class: "button is-dark" %>
  <%= link_to 'SALE', sale_path, class: "button is-danger is-light" %>
  <%= link_to 'NEW', new_path, class: "button is-success is-light" %>
</div>

<%= render 'flowers/flowers' %>

</div>

app/views/home/new.html.erb
<div class="block"> <%=  image_tag("background.jpg", alt: "flower shop")  %></div>


<div class="block p-4">

<%= render 'home/template' %>

<%= link_to 'ALL', root_path, class: "button is-light" %>
<%= link_to 'SALE', sale_path, class: "button is-danger is-light" %>
<%= link_to 'NEW', new_path, class: "button is-success" %>

<%= render "flowers/flowers"%>

</div>

app/views/home/sale.html.erb
<div class="block"> <%=  image_tag("background.jpg", alt: "flower shop")  %></div>


<div class="block p-4">

<%= render 'home/template' %>

<%= link_to 'ALL', root_path, class: "button is-light" %>
<%= link_to 'SALE', sale_path, class: "button is-danger" %>
<%= link_to 'NEW', new_path, class: "button is-success is-light" %>

<%= render "flowers/flowers"%>

</div>