config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'
  get 'contact/show'
  get 'about/show'
  get 'flowers/index'
  get 'flowers/show'

  root to: "home#index"

  get "/about", to: "about#show"
  get "/contact", to: "contact#show"

  get '/index', to:'home#index'
  get '/sale', to:'home#sale'
  get '/new' , to:'home#new'

  resources :flowers, only: [:index, :show] do
    collection do
      get "search"
    end
  end

  post "/cart/checkout", to:'cart#checkout'

  resources :items
  resources :orders
  resources :cart, only: [:create, :checkout, :destroy, :index, :update]
  resources :home
  resources :category

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/about.rb
class About < ApplicationRecord
  validates :description, presence: true
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :order, optional: true
  belongs_to :flower

  validates :price, :quantity, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 0}
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true

  has_many :flowers
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :description, presence:true
end

app/models/customer.rb
class Customer < ApplicationRecord
  validates :username, :password, :role, :first_name, :last_name, :email, :address, presence: true

  belongs_to :province
end

app/models/flower.rb
class Flower < ApplicationRecord

  has_many :cart_items
  belongs_to :category

  validates :name, :price, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 0}

  has_one_attached :image
end

app/models/order.rb
class Order < ApplicationRecord
  validates :subtotal, :total, :status, presence: true
  validates :pst, :gst, :hst, :total, numericality: { greater_than_or_equal_to: 0}

  belongs_to :user
  has_many :cart_items
end

app/models/province.rb
class Province < ApplicationRecord
  validates :name, presence: true
  validates :pst, :gst, :hst, numericality: { greater_than_or_equal_to: 0}

  has_many :customers
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :province
  has_many :orders
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/flowers_helper.rb
module FlowersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar is-fixed-top is-transparent is-hoverable" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="/">
      <p class="title is-1 " style="font-family: Lavishly Yours; color: #7B6986">Blooms</p>
    </a>

    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navMenu">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>


  <div id="navMenu" class="navbar-menu ">
    <div class="navbar-start">

        <%= link_to "Home", root_path, class: "navbar-item" %>

        <%= link_to "Flowers", flowers_path, class: "navbar-item" %>

      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
          Categories
        </a>

        <div class="navbar-dropdown">
            <%= link_to "Bouquets", category_path(:id => 14), class: "navbar-item" %>
          <hr class="navbar-divider">
            <%= link_to "Stems", category_path(:id => 13), class: "navbar-item" %>
          <hr class="navbar-divider">
            <%= link_to "Cascade", category_path(:id => 15), class: "navbar-item" %>
          <hr class="navbar-divider">
            <%= link_to "Composites", category_path(:id => 17), class: "navbar-item" %>
          <hr class="navbar-divider">
            <%= link_to "Pomander", category_path(:id => 16), class: "navbar-item" %>
        </div>
      </div>

      <%= link_to "About", about_path, class: "navbar-item" %>
      <%= link_to "Contact", contact_path, class: "navbar-item" %>


    </div>




     <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
          <%= image_tag("account.png", width:23, alt: "account") %>
        </a>
      <% if user_signed_in? %>

        <div class="navbar-dropdown">
          <p class="navbar-item" >Hi, <%= (current_user.name).capitalize %>!</p>
          <hr class="navbar-divider">
          <%= link_to 'My Orders', orders_path, :class => 'navbar-item' %>
          <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-item' %>
          <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-item'  %>
        </div>
      <% else %>
        <div class="navbar-dropdown">
          <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-item'  %>
          <%= link_to "Login", new_user_session_path, :class => 'navbar-item'  %>
        </div>
      <% end %>
    </div>

      <%= link_to image_tag("cart.png", width:25, alt: "shopping cart") , cart_index_path, class: "navbar-item" %>





  </div>


</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Blooms</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Dancing+Script&family=Lavishly+Yours&family=Playfair+Display&display=swap" rel="stylesheet">
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <div class="mb-6 pb-3"></div>

    <% if notice %>
      <p class="message p-4"><%= notice %></p>
    <% end %>

    <% if alert %>
      <p class="message p-4"><%= alert %></p>
    <% end %>


<div class="block mb-6 pb-6">
    <%= yield %>
</div>

  <nav class="breadcrumb is-small is-centered m-6 p-6" aria-label="breadcrumbs">
    <ul>
      <li><%= link_to "Home", root_path%></li>
      <li><%= link_to "Flowers", flowers_path%></li>
      <li><%= link_to "About", about_path%></li>
      <li><%= link_to "Contact", contact_path%></li>
      <li><a href="#">© 2022 Rasmin Patiu </a></li>
    </ul>
  </nav>
  </body>
</html>